#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALInmobiliaria
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDInmuebles")]
	public partial class DataInmobiliariaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataInmobiliariaDataContext() : 
				base(global::DALInmobiliaria.Properties.Settings.Default.BDInmueblesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataInmobiliariaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataInmobiliariaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataInmobiliariaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataInmobiliariaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DeleteUsuario")]
		public int sp_DeleteUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Int")] System.Nullable<int> activo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, activo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetRoles")]
		public ISingleResult<sp_GetRolesResult> sp_GetRoles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRol);
			return ((ISingleResult<sp_GetRolesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetTipoPropiedad")]
		public ISingleResult<sp_GetTipoPropiedadResult> sp_GetTipoPropiedad([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoPropiedad", DbType="Int")] System.Nullable<int> idTipoPropiedad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoPropiedad);
			return ((ISingleResult<sp_GetTipoPropiedadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetUsuarios")]
		public ISingleResult<sp_GetUsuariosResult> sp_GetUsuarios([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<sp_GetUsuariosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetUsuariosRoles")]
		public ISingleResult<sp_GetUsuariosRolesResult> sp_GetUsuariosRoles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuarioRol", DbType="Int")] System.Nullable<int> idUsuarioRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuarioRol);
			return ((ISingleResult<sp_GetUsuariosRolesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetValidaUsuario")]
		public ISingleResult<sp_GetValidaUsuarioResult> sp_GetValidaUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(200)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password);
			return ((ISingleResult<sp_GetValidaUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertRoles")]
		public int sp_InsertRoles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertTipoPropiedad")]
		public int sp_InsertTipoPropiedad([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertUsuario")]
		public int sp_InsertUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Paterno", DbType="VarChar(50)")] string paterno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Materno", DbType="VarChar(50)")] string materno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreUsuario", DbType="VarChar(50)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(200)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Movil", DbType="VarChar(10)")] string movil, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Int")] System.Nullable<int> activo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, paterno, materno, email, nombreUsuario, password, movil, activo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertUsuariosRoles")]
		public int sp_InsertUsuariosRoles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idRol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateRoles")]
		public int sp_UpdateRoles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRol, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateTipoPropiedad")]
		public int sp_UpdateTipoPropiedad([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoPropiedad", DbType="Int")] System.Nullable<int> idTipoPropiedad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoPropiedad, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateUsuario")]
		public int sp_UpdateUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Paterno", DbType="VarChar(50)")] string paterno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Materno", DbType="VarChar(50)")] string materno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreUsuario", DbType="VarChar(50)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(200)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Movil", DbType="VarChar(10)")] string movil, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Int")] System.Nullable<int> activo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, nombre, paterno, materno, email, nombreUsuario, password, movil, activo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateUsuariosRoles")]
		public int sp_UpdateUsuariosRoles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuarioRol", DbType="Int")] System.Nullable<int> idUsuarioRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuarioRol, idUsuario, idRol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetTiposIdentificacion")]
		public ISingleResult<sp_GetTiposIdentificacionResult> sp_GetTiposIdentificacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoIdentificacion", DbType="Int")] System.Nullable<int> idTipoIdentificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoIdentificacion);
			return ((ISingleResult<sp_GetTiposIdentificacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateTipoIdentificacion")]
		public int sp_UpdateTipoIdentificacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoIdentificacion", DbType="Int")] System.Nullable<int> idTipoIdentificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoIdentificacion, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertTipoIdentificacion")]
		public int sp_InsertTipoIdentificacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetEstatusInmueble")]
		public ISingleResult<sp_GetEstatusInmuebleResult> sp_GetEstatusInmueble()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_GetEstatusInmuebleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetPaises")]
		public ISingleResult<sp_GetPaisesResult> sp_GetPaises()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_GetPaisesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetMunicipios")]
		public ISingleResult<sp_GetMunicipiosResult> sp_GetMunicipios([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEstado", DbType="Int")] System.Nullable<int> idEstado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEstado);
			return ((ISingleResult<sp_GetMunicipiosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetEstados")]
		public ISingleResult<sp_GetEstadosResult> sp_GetEstados()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_GetEstadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetAsentamientos")]
		public ISingleResult<sp_GetAsentamientosResult> sp_GetAsentamientos([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMunicipio", DbType="Int")] System.Nullable<int> idMunicipio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMunicipio);
			return ((ISingleResult<sp_GetAsentamientosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetImagenesInmueble")]
		public ISingleResult<sp_GetImagenesInmuebleResult> sp_GetImagenesInmueble([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInmueble", DbType="Int")] System.Nullable<int> idInmueble)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idInmueble);
			return ((ISingleResult<sp_GetImagenesInmuebleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertDetalleInmueble")]
		public int sp_InsertDetalleInmueble([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumRecamaras", DbType="Int")] System.Nullable<int> numRecamaras, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumBanos", DbType="Int")] System.Nullable<int> numBanos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumServicios", DbType="Int")] System.Nullable<int> numServicios, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumEstacionamientos", DbType="Int")] System.Nullable<int> numEstacionamientos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ConAlberca", DbType="Int")] System.Nullable<int> conAlberca, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumM2", DbType="Int")] System.Nullable<int> numM2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumTotal", DbType="Int")] System.Nullable<int> numTotal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInmueble", DbType="Int")] System.Nullable<int> idInmueble)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numRecamaras, numBanos, numServicios, numEstacionamientos, conAlberca, numM2, numTotal, idInmueble);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertImagenesInmueble")]
		public int sp_InsertImagenesInmueble([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreImagen", DbType="VarChar(50)")] string nombreImagen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UbicacionImagen", DbType="VarChar(100)")] string ubicacionImagen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInmueble", DbType="Int")] System.Nullable<int> idInmueble)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreImagen, ubicacionImagen, idInmueble);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertInmuebles")]
		public int sp_InsertInmuebles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreInmueble", DbType="VarChar(100)")] string nombreInmueble, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(250)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Latitud", DbType="Decimal(18,0)")] System.Nullable<decimal> latitud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Longitud", DbType="Decimal(18,0)")] System.Nullable<decimal> longitud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostoTotal", DbType="Decimal(18,0)")] System.Nullable<decimal> costoTotal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostoMensual", DbType="Decimal(18,0)")] System.Nullable<decimal> costoMensual, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostoMto", DbType="Decimal(18,0)")] System.Nullable<decimal> costoMto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo", DbType="Int")] System.Nullable<int> nuevo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Antiguedad", DbType="Int")] System.Nullable<int> antiguedad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoPropiedad", DbType="Int")] System.Nullable<int> idTipoPropiedad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAsentamiento", DbType="Int")] System.Nullable<int> idAsentamiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEstatusInmueble", DbType="Int")] System.Nullable<int> idEstatusInmueble, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInmueble", DbType="Int")] ref System.Nullable<int> idInmueble)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreInmueble, descripcion, latitud, longitud, costoTotal, costoMensual, costoMto, nuevo, antiguedad, idTipoPropiedad, idAsentamiento, idEstatusInmueble, idInmueble);
			idInmueble = ((System.Nullable<int>)(result.GetParameterValue(12)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateDetalleInmuebles")]
		public int sp_UpdateDetalleInmuebles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDetalleInmueble", DbType="Int")] System.Nullable<int> idDetalleInmueble, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumRecamaras", DbType="Int")] System.Nullable<int> numRecamaras, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumBanos", DbType="Int")] System.Nullable<int> numBanos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumServicios", DbType="Int")] System.Nullable<int> numServicios, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumEstacionamientos", DbType="Int")] System.Nullable<int> numEstacionamientos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ConAlberca", DbType="Int")] System.Nullable<int> conAlberca, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumM2", DbType="Int")] System.Nullable<int> numM2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumTotal", DbType="Int")] System.Nullable<int> numTotal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInmueble", DbType="Int")] System.Nullable<int> idInmueble)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDetalleInmueble, numRecamaras, numBanos, numServicios, numEstacionamientos, conAlberca, numM2, numTotal, idInmueble);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateImagenesInmueble")]
		public int sp_UpdateImagenesInmueble([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdImagenInmueble", DbType="Int")] System.Nullable<int> idImagenInmueble, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreImagen", DbType="VarChar(50)")] string nombreImagen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UbicacionImagen", DbType="VarChar(100)")] string ubicacionImagen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInmueble", DbType="Int")] System.Nullable<int> idInmueble)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idImagenInmueble, nombreImagen, ubicacionImagen, idInmueble);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateInmuebles")]
		public int sp_UpdateInmuebles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInmueble", DbType="Int")] System.Nullable<int> idInmueble, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreInmueble", DbType="VarChar(100)")] string nombreInmueble, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(250)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Latitud", DbType="Decimal(18,0)")] System.Nullable<decimal> latitud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Longitud", DbType="Decimal(18,0)")] System.Nullable<decimal> longitud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostoTotal", DbType="Decimal(18,0)")] System.Nullable<decimal> costoTotal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostoMensual", DbType="Decimal(18,0)")] System.Nullable<decimal> costoMensual, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostoMto", DbType="Decimal(18,0)")] System.Nullable<decimal> costoMto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nuevo", DbType="Int")] System.Nullable<int> nuevo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Antiguedad", DbType="Int")] System.Nullable<int> antiguedad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoPropiedad", DbType="Int")] System.Nullable<int> idTipoPropiedad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAsentamiento", DbType="Int")] System.Nullable<int> idAsentamiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEstatusInmueble", DbType="Int")] System.Nullable<int> idEstatusInmueble)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idInmueble, nombreInmueble, descripcion, latitud, longitud, costoTotal, costoMensual, costoMto, nuevo, antiguedad, idTipoPropiedad, idAsentamiento, idEstatusInmueble);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateUsuariosInmuebles")]
		public int sp_UpdateUsuariosInmuebles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuarioInmueble", DbType="Int")] System.Nullable<int> idUsuarioInmueble, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInmueble", DbType="Int")] System.Nullable<int> idInmueble, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaModificacion", DbType="DateTime")] System.Nullable<System.DateTime> fechaModificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuarioInmueble, idUsuario, idInmueble, fechaModificacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertUsuariosInmuebles")]
		public int sp_InsertUsuariosInmuebles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInmueble", DbType="Int")] System.Nullable<int> idInmueble, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaAlta", DbType="DateTime")] System.Nullable<System.DateTime> fechaAlta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idInmueble, fechaAlta);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetInmuebles")]
		public ISingleResult<sp_GetInmueblesResult> sp_GetInmuebles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInmueble", DbType="Int")] System.Nullable<int> idInmueble)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idInmueble);
			return ((ISingleResult<sp_GetInmueblesResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_GetRolesResult
	{
		
		private int _IdRol;
		
		private string _Descripcion;
		
		public sp_GetRolesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int NOT NULL")]
		public int IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this._IdRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class sp_GetTipoPropiedadResult
	{
		
		private int _IdTipoPropiedad;
		
		private string _Descripcion;
		
		public sp_GetTipoPropiedadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPropiedad", DbType="Int NOT NULL")]
		public int IdTipoPropiedad
		{
			get
			{
				return this._IdTipoPropiedad;
			}
			set
			{
				if ((this._IdTipoPropiedad != value))
				{
					this._IdTipoPropiedad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class sp_GetUsuariosResult
	{
		
		private int _IdUsuario;
		
		private string _Nombre;
		
		private string _Paterno;
		
		private string _Materno;
		
		private string _Email;
		
		private string _NombreUsuario;
		
		private string _Movil;
		
		private string _Password;
		
		private System.Nullable<int> _Activo;
		
		public sp_GetUsuariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paterno", DbType="VarChar(50)")]
		public string Paterno
		{
			get
			{
				return this._Paterno;
			}
			set
			{
				if ((this._Paterno != value))
				{
					this._Paterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materno", DbType="VarChar(50)")]
		public string Materno
		{
			get
			{
				return this._Materno;
			}
			set
			{
				if ((this._Materno != value))
				{
					this._Materno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(50)")]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this._NombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movil", DbType="VarChar(10)")]
		public string Movil
		{
			get
			{
				return this._Movil;
			}
			set
			{
				if ((this._Movil != value))
				{
					this._Movil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(200)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this._Activo = value;
				}
			}
		}
	}
	
	public partial class sp_GetUsuariosRolesResult
	{
		
		private int _IdUsuarioRol;
		
		private int _IdUsuario;
		
		private string _Nombre;
		
		private int _IdRol;
		
		private string _Descripcion;
		
		public sp_GetUsuariosRolesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioRol", DbType="Int NOT NULL")]
		public int IdUsuarioRol
		{
			get
			{
				return this._IdUsuarioRol;
			}
			set
			{
				if ((this._IdUsuarioRol != value))
				{
					this._IdUsuarioRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(101)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int NOT NULL")]
		public int IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this._IdRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class sp_GetValidaUsuarioResult
	{
		
		private int _IdUsuario;
		
		private string _Nombre;
		
		private string _Paterno;
		
		private string _Materno;
		
		private string _Email;
		
		private string _NombreUsuario;
		
		private string _Movil;
		
		private string _Password;
		
		private System.Nullable<int> _Activo;
		
		public sp_GetValidaUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paterno", DbType="VarChar(50)")]
		public string Paterno
		{
			get
			{
				return this._Paterno;
			}
			set
			{
				if ((this._Paterno != value))
				{
					this._Paterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materno", DbType="VarChar(50)")]
		public string Materno
		{
			get
			{
				return this._Materno;
			}
			set
			{
				if ((this._Materno != value))
				{
					this._Materno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(50)")]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this._NombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movil", DbType="VarChar(10)")]
		public string Movil
		{
			get
			{
				return this._Movil;
			}
			set
			{
				if ((this._Movil != value))
				{
					this._Movil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(200)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this._Activo = value;
				}
			}
		}
	}
	
	public partial class sp_GetTiposIdentificacionResult
	{
		
		private int _IdTipoIdentificacion;
		
		private string _Descripcion;
		
		public sp_GetTiposIdentificacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoIdentificacion", DbType="Int NOT NULL")]
		public int IdTipoIdentificacion
		{
			get
			{
				return this._IdTipoIdentificacion;
			}
			set
			{
				if ((this._IdTipoIdentificacion != value))
				{
					this._IdTipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class sp_GetEstatusInmuebleResult
	{
		
		private int _IdEstatusInmueble;
		
		private string _Descripcion;
		
		public sp_GetEstatusInmuebleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstatusInmueble", DbType="Int NOT NULL")]
		public int IdEstatusInmueble
		{
			get
			{
				return this._IdEstatusInmueble;
			}
			set
			{
				if ((this._IdEstatusInmueble != value))
				{
					this._IdEstatusInmueble = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class sp_GetPaisesResult
	{
		
		private int _IdPais;
		
		private string _Descripcion;
		
		public sp_GetPaisesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPais", DbType="Int NOT NULL")]
		public int IdPais
		{
			get
			{
				return this._IdPais;
			}
			set
			{
				if ((this._IdPais != value))
				{
					this._IdPais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class sp_GetMunicipiosResult
	{
		
		private int _IdMunicipio;
		
		private string _Descripcion;
		
		private int _IdEstado;
		
		public sp_GetMunicipiosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMunicipio", DbType="Int NOT NULL")]
		public int IdMunicipio
		{
			get
			{
				return this._IdMunicipio;
			}
			set
			{
				if ((this._IdMunicipio != value))
				{
					this._IdMunicipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Int NOT NULL")]
		public int IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this._IdEstado = value;
				}
			}
		}
	}
	
	public partial class sp_GetEstadosResult
	{
		
		private int _IdEstado;
		
		private string _Descripcion;
		
		private int _IdPais;
		
		public sp_GetEstadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Int NOT NULL")]
		public int IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this._IdEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPais", DbType="Int NOT NULL")]
		public int IdPais
		{
			get
			{
				return this._IdPais;
			}
			set
			{
				if ((this._IdPais != value))
				{
					this._IdPais = value;
				}
			}
		}
	}
	
	public partial class sp_GetAsentamientosResult
	{
		
		private int _IdAsentamiento;
		
		private string _Descripcion;
		
		private string _CP;
		
		private int _IdTipoAsentamiento;
		
		private int _IdMunicipio;
		
		public sp_GetAsentamientosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsentamiento", DbType="Int NOT NULL")]
		public int IdAsentamiento
		{
			get
			{
				return this._IdAsentamiento;
			}
			set
			{
				if ((this._IdAsentamiento != value))
				{
					this._IdAsentamiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CP", DbType="Char(5)")]
		public string CP
		{
			get
			{
				return this._CP;
			}
			set
			{
				if ((this._CP != value))
				{
					this._CP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoAsentamiento", DbType="Int NOT NULL")]
		public int IdTipoAsentamiento
		{
			get
			{
				return this._IdTipoAsentamiento;
			}
			set
			{
				if ((this._IdTipoAsentamiento != value))
				{
					this._IdTipoAsentamiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMunicipio", DbType="Int NOT NULL")]
		public int IdMunicipio
		{
			get
			{
				return this._IdMunicipio;
			}
			set
			{
				if ((this._IdMunicipio != value))
				{
					this._IdMunicipio = value;
				}
			}
		}
	}
	
	public partial class sp_GetImagenesInmuebleResult
	{
		
		private int _IdImagenInmueble;
		
		private string _NombreImagen;
		
		private string _UbicacionImagen;
		
		private int _IdInmueble;
		
		public sp_GetImagenesInmuebleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImagenInmueble", DbType="Int NOT NULL")]
		public int IdImagenInmueble
		{
			get
			{
				return this._IdImagenInmueble;
			}
			set
			{
				if ((this._IdImagenInmueble != value))
				{
					this._IdImagenInmueble = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreImagen", DbType="VarChar(50)")]
		public string NombreImagen
		{
			get
			{
				return this._NombreImagen;
			}
			set
			{
				if ((this._NombreImagen != value))
				{
					this._NombreImagen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UbicacionImagen", DbType="VarChar(100)")]
		public string UbicacionImagen
		{
			get
			{
				return this._UbicacionImagen;
			}
			set
			{
				if ((this._UbicacionImagen != value))
				{
					this._UbicacionImagen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInmueble", DbType="Int NOT NULL")]
		public int IdInmueble
		{
			get
			{
				return this._IdInmueble;
			}
			set
			{
				if ((this._IdInmueble != value))
				{
					this._IdInmueble = value;
				}
			}
		}
	}
	
	public partial class sp_GetInmueblesResult
	{
		
		private int _IdInmueble;
		
		private string _NombreInmueble;
		
		private string _Descripcion;
		
		private System.Nullable<decimal> _Latitud;
		
		private System.Nullable<decimal> _Longitud;
		
		private System.Nullable<decimal> _CostoTotal;
		
		private System.Nullable<decimal> _CostoMensual;
		
		private System.Nullable<decimal> _CostoMto;
		
		private System.Nullable<int> _Nuevo;
		
		private System.Nullable<int> _Antiguedad;
		
		private int _IdTipoPropiedad;
		
		private int _IdAsentamiento;
		
		private int _IdEstatusInmueble;
		
		private System.Nullable<int> _NumRecamaras;
		
		private System.Nullable<int> _NumBanos;
		
		private System.Nullable<int> _NumServicios;
		
		private System.Nullable<int> _NumEstacionamientos;
		
		private System.Nullable<int> _ConAlberca;
		
		private System.Nullable<int> _NumM2;
		
		private System.Nullable<int> _NumTotal;
		
		private int _IdImagenInmueble;
		
		private string _NombreImagen;
		
		private string _UbicacionImagen;
		
		private System.Nullable<System.DateTime> _FechaAlta;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
		private int _IdUsuario;
		
		private string _Nombre;
		
		public sp_GetInmueblesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInmueble", DbType="Int NOT NULL")]
		public int IdInmueble
		{
			get
			{
				return this._IdInmueble;
			}
			set
			{
				if ((this._IdInmueble != value))
				{
					this._IdInmueble = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreInmueble", DbType="VarChar(100)")]
		public string NombreInmueble
		{
			get
			{
				return this._NombreInmueble;
			}
			set
			{
				if ((this._NombreInmueble != value))
				{
					this._NombreInmueble = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(250)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitud", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Latitud
		{
			get
			{
				return this._Latitud;
			}
			set
			{
				if ((this._Latitud != value))
				{
					this._Latitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitud", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Longitud
		{
			get
			{
				return this._Longitud;
			}
			set
			{
				if ((this._Longitud != value))
				{
					this._Longitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoTotal", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CostoTotal
		{
			get
			{
				return this._CostoTotal;
			}
			set
			{
				if ((this._CostoTotal != value))
				{
					this._CostoTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoMensual", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CostoMensual
		{
			get
			{
				return this._CostoMensual;
			}
			set
			{
				if ((this._CostoMensual != value))
				{
					this._CostoMensual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoMto", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CostoMto
		{
			get
			{
				return this._CostoMto;
			}
			set
			{
				if ((this._CostoMto != value))
				{
					this._CostoMto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nuevo", DbType="Int")]
		public System.Nullable<int> Nuevo
		{
			get
			{
				return this._Nuevo;
			}
			set
			{
				if ((this._Nuevo != value))
				{
					this._Nuevo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Antiguedad", DbType="Int")]
		public System.Nullable<int> Antiguedad
		{
			get
			{
				return this._Antiguedad;
			}
			set
			{
				if ((this._Antiguedad != value))
				{
					this._Antiguedad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPropiedad", DbType="Int NOT NULL")]
		public int IdTipoPropiedad
		{
			get
			{
				return this._IdTipoPropiedad;
			}
			set
			{
				if ((this._IdTipoPropiedad != value))
				{
					this._IdTipoPropiedad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsentamiento", DbType="Int NOT NULL")]
		public int IdAsentamiento
		{
			get
			{
				return this._IdAsentamiento;
			}
			set
			{
				if ((this._IdAsentamiento != value))
				{
					this._IdAsentamiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstatusInmueble", DbType="Int NOT NULL")]
		public int IdEstatusInmueble
		{
			get
			{
				return this._IdEstatusInmueble;
			}
			set
			{
				if ((this._IdEstatusInmueble != value))
				{
					this._IdEstatusInmueble = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumRecamaras", DbType="Int")]
		public System.Nullable<int> NumRecamaras
		{
			get
			{
				return this._NumRecamaras;
			}
			set
			{
				if ((this._NumRecamaras != value))
				{
					this._NumRecamaras = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumBanos", DbType="Int")]
		public System.Nullable<int> NumBanos
		{
			get
			{
				return this._NumBanos;
			}
			set
			{
				if ((this._NumBanos != value))
				{
					this._NumBanos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumServicios", DbType="Int")]
		public System.Nullable<int> NumServicios
		{
			get
			{
				return this._NumServicios;
			}
			set
			{
				if ((this._NumServicios != value))
				{
					this._NumServicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumEstacionamientos", DbType="Int")]
		public System.Nullable<int> NumEstacionamientos
		{
			get
			{
				return this._NumEstacionamientos;
			}
			set
			{
				if ((this._NumEstacionamientos != value))
				{
					this._NumEstacionamientos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConAlberca", DbType="Int")]
		public System.Nullable<int> ConAlberca
		{
			get
			{
				return this._ConAlberca;
			}
			set
			{
				if ((this._ConAlberca != value))
				{
					this._ConAlberca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumM2", DbType="Int")]
		public System.Nullable<int> NumM2
		{
			get
			{
				return this._NumM2;
			}
			set
			{
				if ((this._NumM2 != value))
				{
					this._NumM2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumTotal", DbType="Int")]
		public System.Nullable<int> NumTotal
		{
			get
			{
				return this._NumTotal;
			}
			set
			{
				if ((this._NumTotal != value))
				{
					this._NumTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImagenInmueble", DbType="Int NOT NULL")]
		public int IdImagenInmueble
		{
			get
			{
				return this._IdImagenInmueble;
			}
			set
			{
				if ((this._IdImagenInmueble != value))
				{
					this._IdImagenInmueble = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreImagen", DbType="VarChar(50)")]
		public string NombreImagen
		{
			get
			{
				return this._NombreImagen;
			}
			set
			{
				if ((this._NombreImagen != value))
				{
					this._NombreImagen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UbicacionImagen", DbType="VarChar(100)")]
		public string UbicacionImagen
		{
			get
			{
				return this._UbicacionImagen;
			}
			set
			{
				if ((this._UbicacionImagen != value))
				{
					this._UbicacionImagen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAlta", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAlta
		{
			get
			{
				return this._FechaAlta;
			}
			set
			{
				if ((this._FechaAlta != value))
				{
					this._FechaAlta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this._FechaModificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
